name: Lotto Data Update

on: 
  repository_dispatch: 
    types: [trigger_crawling]
  # schedule:
    # 매주 토요일 한국 시간 밤 8시35분경 실행 (UTC 기준 11:30)
    # - cron: '35 11 * * 6'
  workflow_dispatch: # 수동으로도 실행 가능하게 설정

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT_TOKEN}}

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 필수 라이브러리 설치
        run: pip install argparse pathlib requests typing

      - name: 크롤링 실행
        run: python /home/runner/work/lotto_crawler/lotto_crawler/crawler.py --start 1220

      - name: 변경된 데이터를 저장소에 업데이트
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add lotto_results.csv
          git commit -m "Update lotto data" || echo "No changes to commit"
          git push
